// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhgU6AdK_DtMbGEzn8mnveicpGAtgIkBw',
    appId: '1:899441682307:web:2d3292386adce4c69838b6',
    messagingSenderId: '899441682307',
    projectId: 'esp32-solar-telemetry',
    authDomain: 'esp32-solar-telemetry.firebaseapp.com',
    databaseURL: 'https://esp32-solar-telemetry-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-solar-telemetry.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCog3sLGEeAdG4FRfCavIPhWBhQwCKxki4',
    appId: '1:899441682307:android:7220281b58effb6c9838b6',
    messagingSenderId: '899441682307',
    projectId: 'esp32-solar-telemetry',
    databaseURL: 'https://esp32-solar-telemetry-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-solar-telemetry.firebasestorage.app',
  );
}
